### ISSUE TITLE
Windows cannot verify the digital signature

### ISSUE THREAD

**Issue by robo2bobo** [OpenVPN/tap-windows6#102]
Hello,

I made the unfortunate mistake of upgrading from an older version of openvpn to the latest 2.4.8, under Windows 7 (ultimate, service pack 1). The machine has no internet access, its only being used internally.

What happened is, openvpn installed ok but the TAP interface disappeared. The device manager shows a yellow triangle with an exclamation, next to the TAP-Windows Adapter V9, and the device status says:

```
Windows cannot verify the digital signature for the drivers required for this device. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (Code 52)
```

Anyone knows if its possible to recover from this situation? 

Thank you.

**Comment by selvanair** [comment]
Windows SP1 is very old and will not support SHA256 signature without a hotfix. Try applying [KB2921916](https://support.microsoft.com/en-us/help/2921916/the-untrusted-publisher-dialog-box-appears-when-you-install-a-driver-i)  if you can still find it somewhere.

**Comment by robo2bobo** [comment]
Ah I see. It would have been nice to have a warning in the installer, to stop me from continuing with the installation.

As a temporary measure, I found the older TAP driver in filestorage and that worked fine with openvpn 2.4.8.

I'll go look for KB2921916, thank you for your help.
