### ISSUE TITLE
when use intel wireless AC8265 and AC 7265 with HP PC will run erro

### ISSUE THREAD

**Issue by timeforasong** [OpenVPN/tap-windows6#104]
I have two HP computers. When I use one of the devices with Intel AC 8265 wireless network card model, the wireless network will stop working automatically after I start TAP, but it can work normally when I use the network cable. When I start tap with Intel AC 7260 wireless network card model and use WiFi, there will be no exception. What's the reason? What is the orientation of the analysis?

**Comment by timeforasong** [comment]
when i use another PC with Intel AC 7265 ,the same error occured

**Comment by schwabe** [comment]
See other issues. IIrc there is a problem with a HP management software that disables network interfaces because it thinks the tap adapter is a wired connection. The newest version of the adapter driver should fix this.

**Comment by timeforasong** [comment]
> See other issues. IIrc there is a problem with a HP management software that disables network interfaces because it thinks the tap adapter is a wired connection. The newest version of the adapter driver should fix this.

“See other issues”，Can you give me this link about  HP management software?

**Comment by schwabe** [comment]
Read the discussion here: https://github.com/OpenVPN/tap-windows6/pull/94

I have no first hand experience with HP management software and cannot provide you with links for that. You will have to contact HP support for that.

**Comment by timeforasong** [comment]
> Read the discussion here: #94
> 
> I have no first hand experience with HP management software and cannot provide you with links for that. You will have to contact HP support for that.

Thank you very much!

**Comment by timeforasong** [comment]
Thank you schwabe. It works.
