### ISSUE TITLE
install error Device has problem: 0x38 (CM_PROB_NEED_CLASS_CONFIG)

### ISSUE THREAD

**Issue by wkingnet** [OpenVPN/tap-windows6#107]
After I installed other VPN using openVPN technology, I can no longer install the latest openVPN. I looked up other issues and it seems there is no workaround. I read the setupapi.dev.log and I don't think I got certificate errors. But the error does not indicate how to resolve. So is there any other solution? For example, delete some files, registry keys?

attach is  setupapi.dev.log

Best regards

[1.log](https://github.com/OpenVPN/tap-windows6/files/4310735/1.log)

**Comment by wkingnet** [comment]
I have uninstalled other VPNs but still cannot install openVPN

**Comment by rozmansi** [comment]
The ROOT\NET\0000 (your TAP adapter) needed a device restart after the driver update. That's normal. However, it reported `Device has problem: 0x38 (CM_PROB_NEED_CLASS_CONFIG)`, followed by a timeout waiting for device post-install to complete.

Anyway, I have no clue how to reproduce it, but would suggest to clean up the computer before trying to install it again:

1. Open the Device Manager, locate Network Adapters and remove all "TAP-Windows Adapter V9" adapters. Do not select to remove the driver too until the last adapter. The log above shows you have only one, right?

2. Open an elevated command prompt and use `pnputil -e` and `pnputil -d oem##.inf` to remove all TAP-Windows6 drivers.

**Comment by wkingnet** [comment]
I successfully solved this problem. This is not caused by openVPN. It is because there is a malicious program on my computer disguised as a driver, which prevents the installation of the openVPN driver. After I cleaned up the malicious program driver, openVPN was successfully installed.

Thank you very much for your support and have a nice day.

Best regards
