### ISSUE TITLE
Prebuilt Binary Location?

### ISSUE THREAD

**Issue by duaneellissd** [OpenVPN/tap-windows6#108]
I am confused about a few things.

A number of the openvpn web pages seem point to "prebuilts" for this package - I can't seem to find one named "tap-windows6<someversion>.exe"

For example: https://community.openvpn.net/openvpn/wiki/GettingTapWindows
I do see for example "tap-windows-<someversion>.exe" but not the 6 version.

My question is - where is the latest "offical signed released" driver located?

Note: My end goal is to use just the "tap" driver with an different application, not "openvpn" 

If the answer/solution is - I must install the entire openvpn package...  because it contains the driver and that is the only solution - please let me know.

**Comment by TinCanTech** [comment]
Please see: https://build.openvpn.net/downloads/releases/

**Comment by duaneellissd** [comment]
That is exactly where I looked - I specifically see:   tap-windows-9.24.2-I601-Win10.exe

Which is *NOT*  tap-windows6 - it is I believe the older solution, NDIS5 not NDIS6

And I believe if I am getting started with something I should be using  tap-windows6-<SOMENUMBER>.

Do I misunderstand?

**Comment by mattock** [comment]
@duaneellissd it _is_ tap-windows6. Tap-windows6 (NDIS 6) code _is_ based on tap-windows (NDIS 5) code and the driver name in Windows is the same. That probably explains the installer was never renamed.

Version 9.9.x are tap-windows  (NDIS 5) and everything above 9.20.x are tap-windows6 (NDIS 6).
