### ISSUE TITLE
How to install multiple taps & naming etc

### ISSUE THREAD

**Issue by duaneellissd** [OpenVPN/tap-windows6#110]
I need to install 4 identical taps, so that I can create 4 different interfaces.

**Background** 
I need to create 4 SLIP network adapters on windows, ie:  "tap-tun -> SERIALPORT" - If there is an existing solution - great - but I can't find one.

**Known and Unknown**

- Executing as Administrator.
- No modification of INF, CAT or SYS files
- copied the "addtap.bat" file creating "add4taps.bat", and changed "tapname" parameter.

**The output I get is this:**
```
c:\Program Files\TAP-Windows\bin>tapinstall install ..\driver\OemVista.inf  tap0001
Device node created. Install is complete when drivers are installed...
Updating drivers for tap0001 from c:\Program Files\TAP-Windows\driver\OemVista.inf.
tapinstall failed.

c:\Program Files\TAP-Windows\bin>
```

**Comment by mattock** [comment]
@rozmansi may be able to tell if PR https://github.com/OpenVPN/tap-windows6/pull/106 helps resolve this kind of challenges.

**Comment by schwabe** [comment]
the id is always tap0901 iirc. You are trying to install a different driver with changing the id: See also here https://community.openvpn.net/openvpn/wiki/ManagingWindowsTAPDrivers

**Comment by duaneellissd** [comment]
Thanks @schwabe  - that sounds like what I want.

In my case I have 1 PC, with a number of USB-SERIAL devices (radios)
I want to create one tap for each radio.

**Problem/Question:**  where do I find "tapctrl.exe" - it is not included with the installer/exe.

It would be most helpful if it was included in the tap installer (EXE) but it is not.

**Comment by rozmansi** [comment]
tapctl.exe will be deployed starting with the OpenVPN 2.5.

**Comment by duaneellissd** [comment]
@rozmansi  - Thanks for the update.
