### ISSUE TITLE
TAP Adapter 9.24.* has 1 GB limitation

### ISSUE THREAD

**Issue by eichgee** [OpenVPN/tap-windows6#113]
i use tun2socks with tap adapter to work as vpn, the issue comes when it reached 1 gb network usage then its stopped sending and receiving after that unless i try to reconnect again, so i tried to reinstall the tap adapter driver with version 9.23.* and it worked. it could pass 1 GB, is the issue comes from TAP Adapter or Tun2socks? i can't tell

i use windows 10 64-bit version 10.0.18363.752 if that's in the case

**Comment by cron2** [comment]
hi,

On Thu, Apr 23, 2020 at 11:50:19AM -0700, eichgee wrote:
> i use tun2socks with tap adapter to work as vpn, the issue comes when it reached 1 gb network usage then its stopped sending and receiving after that unless i try to reconnect again, so i tried to reinstall the tap adapter driver with version 9.23.* and it worked. it could pass 1 GB, is the issue comes from TAP Adapter or Tun2socks? i can't tell
> 
> i use windows 10 64-bit version 10.0.18363.752 if that's in the case

Generally speaking there are no volume limits in the TAP driver.

(If used with OpenVPN, there might be a tls-renegotiation going on after
some gbytes, but this is independent of the TAP driver version, depending
only on OpenVPN config)

gert

-- 
"If was one thing all people took for granted, was conviction that if you 
 feed honest figures into a computer, honest figures come out. Never doubted 
 it myself till I met a computer with a sense of humor."
                             Robert A. Heinlein, The Moon is a Harsh Mistress

Gert Doering - Munich, Germany                             gert@greenie.muc.de
