### ISSUE TITLE
I do change version.m4 and build successfully, but it seems to collide with the original network interface driver

### ISSUE THREAD

**Issue by what951006** [OpenVPN/tap-windows6#123]
If the original network interface driver existed, I can't manage to install my driver~ Do I need to modify like ClassGUID sort of things?

**Comment by selvanair** [comment]
Depends on what you want to do. If you are just updating the tap-windows6 driver with your own version, changing the version number and date should be enough. The tapctl.exe utility always selects the "best" driver in the store, but you can force any version using devcon (or tapinstall).

If you want to create a separate set of adapters that could co-exist with tap-windows6 adapters with independent drivers,  you have to do more. Essentially the hardware id should be changed as all device nodes with same hwid will get the same driver.  Read the "note to developers" section in the inf file. 

Do not change the class id as that is of the NET class the driver belongs to.

**Comment by what951006** [comment]
> Depends on what you want to do. If you are just updating the tap-windows6 driver with your own version, changing the version number and date should be enough. The tapctl.exe utility always selects the "best" driver in the store, but you can force any version using devcon (or tapinstall).
> 
> If you want to create a separate set of adapters that could co-exist with tap-windows6 adapters with independent drivers, you have to do more. Essentially the hardware id should be changed as all device nodes with same hwid will get the same driver. Read the "note to developers" section in the inf file.
> 
> Do not change the class id as that is of the NET class the driver belongs to.

I just write

**Comment by what951006** [comment]
> Depends on what you want to do. If you are just updating the tap-windows6 driver with your own version, changing the version number and date should be enough. The tapctl.exe utility always selects the "best" driver in the store, but you can force any version using devcon (or tapinstall).
> 
> If you want to create a separate set of adapters that could co-exist with tap-windows6 adapters with independent drivers, you have to do more. Essentially the hardware id should be changed as all device nodes with same hwid will get the same driver. Read the "note to developers" section in the inf file.
> 
> Do not change the class id as that is of the NET class the driver belongs to.

much obliged!
