### ISSUE TITLE
VCRUNTIME missing when installing tap driver

### ISSUE THREAD

**Issue by shkpk** [OpenVPN/tap-windows6#134]
I recently compiled tap driver and made package with NSIS as written in README file. However installation of .exe failed on some windows machine with VCRUNTIME  error which is because those machines do not have vc_redist package not installed already.

Any idea how this can be resolved? NSIS should be adding dependencies in exe.

**Comment by mattock** [comment]
I vaguely recall we had the same problem years ago. Cannot remember how it was resolved. I also could not find any traces of the issue from our [bug tracker](https://community.openvpn.net/).

**Comment by mattock** [comment]
Well, to be honest I can recall if the problem was with tap-windows(6) or OpenVPN.

**Comment by shkpk** [comment]
Problem seems to be when compiling devcon.exe from https://github.com/OpenVPN/Windows-driver-samples
I use pre-built devcon.exe from EWDK 2017, and this error is gone.

**Comment by shkpk** [comment]
@mattock  Apparently this commit doesnt work as it should.
https://github.com/OpenVPN/Windows-driver-samples/commit/f4caadeffb5b14b50ae37de5c9c06d72ead6a149?branch=f4caadeffb5b14b50ae37de5c9c06d72ead6a149&diff=split

**Comment by mattock** [comment]
As mentioned in the commit comments the commit/patch for Windows-driver-samples  is _currently_ working ok for us. Otherwise we'd have a flood of user complaints. But it is possible that some WDK versions manage do not interpret the settings correctly and cause the vc_redist issue to reappear.

**Comment by shkpk** [comment]
@mattock  yes, i figured out. your commit is good, there was problem with WDK I was using. Closing this ticket.
