### ISSUE TITLE
Build with self-signed certificate

### ISSUE THREAD

**Issue by Jimmy01240397** [OpenVPN/tap-windows6#160]
Because of some urgent matter I need to build with self-signed certificate, but I get this message.

`python2 buildtap.py -b -p --ti=devcon --sdk=WDK --sign --crosscert=C:\Users\test\Desktop\selfsigndrivercert.cer --cert openvpn.chumy --timestamp http://timestamp.sectigo.com`

![image](https://user-images.githubusercontent.com/57281249/233815184-7cfcd187-1299-4eb9-a1fe-f8fda603e3fa.png)

![image](https://user-images.githubusercontent.com/57281249/233815215-787055ec-c79d-4665-91e2-a272074740dc.png)

Here is my [certificate](https://github.com/OpenVPN/tap-windows6/files/11302653/selfsigndrivercert.zip)

what should I do.

**Comment by cron2** [comment]
I can only guess - maybe it is sufficient to import the `openvpn.chumy` into the `trusted roots` certificate store?

**Comment by lstipakov** [comment]
Which OS is that?

- If this is Windows 7, my understanding is that you are [out of luck](https://www.osr.com/blog/2020/10/15/microsoft-driver-updates-allowed-win7-win8/).
- For Windows 10 you need either to enable test signing or do proper signing on Microsoft portal.

**Comment by cron2** [comment]
https://www.osr.com/blog/2021/04/08/lost-cause-no-driver-updates-allowed-except-for-win-10/

**Comment by Jimmy01240397** [comment]
Because OpenVPN GUI installer had update. So I will close this issue.
