### ISSUE TITLE
Missing devcon.exe for i386 & arm64 for Win10+

### ISSUE THREAD

**Issue by alexgit2k** [OpenVPN/tap-windows6#168]
With release 9.27.0 the assets also includes the drivers for Windows 10+:
https://github.com/OpenVPN/tap-windows6/releases/download/9.27.0/dist.win10.zip

`devcon.exe` to install the drivers is only available in the amd64-directory, but not included for i386 & arm64. Can you please also supply it for the other architectures.

**Comment by lstipakov** [comment]
Updated `dist.win10.zip` and added `devcon.exe` to `i386` and `arm64` directories.
