### ISSUE TITLE
Latest tap-windows-9.21.2 adapter doesnt work on Windows 10

### ISSUE THREAD

**Issue by jackalmeida** [OpenVPN/tap-windows6#19]
I tried the latest tap-windows-9.21.2.zip to install on Windows 10 mannuly:

-----------------------------------------------------------------------------------------
C:\>tapinstall.exe install OemVista.inf TAP0901
Device node created. Install is complete when drivers are installed...
Updating drivers for TAP0901 from C:\OemVista.inf.
Drivers installed successfully.
-----------------------------------------------------------------------------------------

From the commands , looks like its sucessfully installed,  also i can see the new created tap connection.
but when i try to use openvpn to connect,  i always got notification :   No TAP adapters found.
i also tried the other tap driver based client like openconnect got the same kind of errors...
also tried 3 different version of win 10,  all the same notification....
it only happens on win 10,  the other windows versions all fine,  from xp to win 8.1.......

btw 1 weird thing is:
the notification i got its only from doing mannuly installation from tap-windows-9.21.2.zip
which provided these files:
tapinstall.exe
OemVista
tap0901.inf
tap0901.sys

But
the tap-windows-9.21.2.exe auto installer from 
https://openvpn.net/index.php/download/community-downloads.html
works fine on win10.

tapinstall.exe
OemVista
tap0901.inf
tap0901.sys

these files are all the same,  i double compared md5 from the  .zip and the .exe autoinstaller.
so very weird that the command created tap adpter connection doesnt work:
tapinstall.exe install OemVista.inf TAP0901

anyone knows how does the auto installer work on win 10?
i guess it has something to do with regedit...

**Comment by mattock** [comment]
The installer's NSI script is available [here](https://github.com/OpenVPN/tap-windows6/blob/master/installer/tap-windows6.nsi). Based on a quick look the installer just runs tapinstall.exe, adds some shortcuts and registers tap-windows6 to "Add/Remove programs". So you should be able to install the driver using the [normal manual procedure](https://community.openvpn.net/openvpn/wiki/ManagingWindowsTAPDrivers) (as admin).

One thing worth checking is the Authenticode signature of the catalog (.cat) file. A cursory check can be done using Powershell:

    Get-AuthenticodeSignature tap0901.cat

The file should have two signatures (SHA1 and SHA2), and if I recall correctly, above command should show the fingerprint of both, and say that both are "Valid". More detailed information can be obtained using "File properties" dialog in Windows Explorer.

**Comment by jackalmeida** [comment]
Hi mattock,

Great thanks for your fast reply.
I checked the installer's NSI script,  
I noticed the only differences are:

I used the command on Win 10:

tapinstall.exe install OemVista.inf TAP0901

but the NSI script used {PRODUCT_TAP_WIN_COMPONENT_ID} instead of TAP0901:

tapinstall.exe install OemVista.inf {PRODUCT_TAP_WIN_COMPONENT_ID}



How does the script to get the value of {PRODUCT_TAP_WIN_COMPONENT_ID} plz ?
Do you think the issue its i used  TAP0901 as the component id on win10?

Thanks a lot!

**Comment by mattock** [comment]
_PRODUCT_TAP_WIN_COMPONENT_ID_ is _tap0901_. The only difference is that you used uppercase. and the installer uses lowercase letters.

**Comment by jackalmeida** [comment]
Great thanks !!! i fixed this problem,   its all becasue of the uppercase,   i changed that to lowercase, and it works now.   thanks again mottock

**Comment by jackalmeida** [comment]
but its really weird that on Windows 10,  the uppercase or lowercase matters.................

**Comment by mattock** [comment]
Good you got it sorted out!
