### ISSUE TITLE
tap-windows6 9.21.0 hangs forever when writing

### ISSUE THREAD

**Issue by dechamps** [OpenVPN/tap-windows6#3]
I installed a virtual network device using tap-windows6 9.21.0 (from the [OpenVPN Experimental versions page](https://community.openvpn.net/openvpn/wiki/ExperimentalVersions)) on my Windows 7 x64 system. Unfortunately, every time I try to write a packet to the device handle, it hangs forever.

I wrote [a small program](https://gist.github.com/dechamps/c4e9adb432c09dc3f1c8) to reproduce the issue. All the program does is open the device, enable it, read one packet, write the packet back, and close the device. Here's the output with tap-windows6 9.21.0:

```
>tap-win32-test.exe {FE35ADE5-E728-4DAC-9ABA-6C29C2EBE8D3}
Opening device with path: \\.\Global\{FE35ADE5-E728-4DAC-9ABA-6C29C2EBE8D3}.tap
Device successfully opened
Setting media status to connected
Media status set
Reading one packet
Successfully read one packet of size 42
Writing the packet back
```

It then hangs forever. Not only that, but the process cannot be killed, leading me to believe the driver state is messed up. (As a side note, the packet size that it reads (42) looks suspicious - I did not check the contents)

In contrast, here's the output on the same system with the driver included in the latest stable OpenVPN (2.3.4, driver version 9.0.0.9):

```
>tap-win32-test.exe {2D55947C-C6E0-483B-8978-7417BE0BDD9C}
Opening device with path: \\.\Global\{2D55947C-C6E0-483B-8978-7417BE0BDD9C}.tap
Device successfully opened
Setting media status to connected
Media status set
Reading one packet
Successfully read one packet of size 342
Writing the packet back
Successfully wrote 342 bytes
Closing device
```

**Comment by SviMik** [comment]
I think I'm hitting the same bug, and my driver version is 9.0.0.9, which makes it likely to be the case.
1. Is there any workaround I can make in my app so it would still (at least somehow) work with older drivers?
2. Is there any explanation why it is working with OpenVPN just fine (except for a few rare cases) but fails immediately in this example?
