### ISSUE TITLE
Windows 10?

### ISSUE THREAD

**Issue by kanoi** [OpenVPN/tap-windows6#8]
Windows 10?

**Comment by cron2** [comment]
Hi,

On Tue, Aug 04, 2015 at 10:06:11PM -0700, kanoi wrote:
> Windows 10?

Yes...?  What is the question?

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by kanoi** [comment]
Is it planned?
I can't seem to find any information about it for windows 10 and have had someone upgrade from 7 to 10 and found it didn't work (so I got them to do the roll back to windows 7 and that solved it of course) - so I'm guessing the tap needs updating since there are no changes for a long time

**Comment by cron2** [comment]
Hi,

On Wed, Aug 05, 2015 at 09:10:06AM -0700, kanoi wrote:
> Is it planned?
> I can't seem to find any information about it for windows 10 and have had someone upgrade from 7 to 10 and found it didn't work (so I got them to do the roll back to windows 7 and that solved it of course) - so I'm guessing the tap needs updating since there are no changes for a long time

We do not know any reasons why it should *not* work on Win10 - so if it
does not work, please open a bug in our bugtracker (community.openvpn.net)
and describe the symptoms...

gert

-- 
USENET is *not* the non-clickable part of WWW!
                                                           //www.muc.de/~gert/
Gert Doering - Munich, Germany                             gert@greenie.muc.de
fax: +49-89-35655025                        gert@net.informatik.tu-muenchen.de

**Comment by kanoi** [comment]
Thanks I'll track down and look there at community for information.
